// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ParcelProcessor.Communications.Kafka.Dto
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class CurrentState : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"CurrentState\",\"namespace\":\"ParcelProcessor.Communication" +
				"s.Kafka.Dto\",\"fields\":[{\"name\":\"Facility\",\"type\":{\"type\":\"enum\",\"name\":\"Facility" +
				"\",\"namespace\":\"ParcelProcessor.Communications.Kafka.Dto\",\"symbols\":[\"Ord\",\"Dfw\"," +
				"\"Atl\"]}}]}");
		private ParcelProcessor.Communications.Kafka.Dto.Facility _Facility;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return CurrentState._SCHEMA;
			}
		}
		public ParcelProcessor.Communications.Kafka.Dto.Facility Facility
		{
			get
			{
				return this._Facility;
			}
			set
			{
				this._Facility = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Facility;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Facility = (ParcelProcessor.Communications.Kafka.Dto.Facility)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
