// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ParcelProcessor.Communications.Kafka.Dto
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class ParcelScheme : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ParcelScheme"",""namespace"":""ParcelProcessor.Communications.Kafka.Dto"",""fields"":[{""name"":""_Id"",""type"":""string""},{""name"":""Identifiers"",""type"":{""type"":""record"",""name"":""Identifiers"",""namespace"":""ParcelProcessor.Communications.Kafka.Dto"",""fields"":[{""name"":""UPID"",""type"":""string""},{""name"":""Barcode"",""type"":""string""}]}},{""name"":""Attributes"",""type"":{""type"":""record"",""name"":""Attributes"",""namespace"":""ParcelProcessor.Communications.Kafka.Dto"",""fields"":[{""name"":""Weight"",""type"":""float""},{""name"":""Width"",""type"":""float""},{""name"":""Length"",""type"":""float""},{""name"":""Depth"",""type"":""float""}]}},{""name"":""CurrentState"",""type"":{""type"":""record"",""name"":""CurrentState"",""namespace"":""ParcelProcessor.Communications.Kafka.Dto"",""fields"":[{""name"":""Facility"",""type"":{""type"":""enum"",""name"":""Facility"",""namespace"":""ParcelProcessor.Communications.Kafka.Dto"",""symbols"":[""Ord"",""Dfw"",""Atl""]}}]}}]}");
		private string @__Id;
		private ParcelProcessor.Communications.Kafka.Dto.Identifiers _Identifiers;
		private ParcelProcessor.Communications.Kafka.Dto.Attributes _Attributes;
		private ParcelProcessor.Communications.Kafka.Dto.CurrentState _CurrentState;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ParcelScheme._SCHEMA;
			}
		}
		public string _Id
		{
			get
			{
				return this.@__Id;
			}
			set
			{
				this.@__Id = value;
			}
		}
		public ParcelProcessor.Communications.Kafka.Dto.Identifiers Identifiers
		{
			get
			{
				return this._Identifiers;
			}
			set
			{
				this._Identifiers = value;
			}
		}
		public ParcelProcessor.Communications.Kafka.Dto.Attributes Attributes
		{
			get
			{
				return this._Attributes;
			}
			set
			{
				this._Attributes = value;
			}
		}
		public ParcelProcessor.Communications.Kafka.Dto.CurrentState CurrentState
		{
			get
			{
				return this._CurrentState;
			}
			set
			{
				this._CurrentState = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._Id;
			case 1: return this.Identifiers;
			case 2: return this.Attributes;
			case 3: return this.CurrentState;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._Id = (System.String)fieldValue; break;
			case 1: this.Identifiers = (ParcelProcessor.Communications.Kafka.Dto.Identifiers)fieldValue; break;
			case 2: this.Attributes = (ParcelProcessor.Communications.Kafka.Dto.Attributes)fieldValue; break;
			case 3: this.CurrentState = (ParcelProcessor.Communications.Kafka.Dto.CurrentState)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
