services:
  facilityworker:
    image: facilityworker
    container_name: FacilityWorker
    build:
      context: .
      dockerfile: ./FacilityWorker/FacilityWorker/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env

  parcelprocessor:
    image: parcelprocessor
    container_name: ParcelProcessor
    build:
      context: .
      dockerfile: ./ParcelProcessor/ParcelProcessor/Dockerfile
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbit
    hostname: "rabbit"
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"

  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  schemaregistry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schemaregistry 
    hostname: schemaregistry
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8085:8085

  schemaregistry-ui:
      image: landoop/schema-registry-ui
      container_name: schemaregistry-ui
      ports:
        - 8000:8000
      environment:
        SCHEMAREGISTRY_URL: http://schemaregistry:8085
        ALLOW_GLOBAL: 1
        ALLOW_TRANSITIVE: 1
        ALLOW_DELETION: 1
        READONLY_MODE: 0
        PROXY: 'true'

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka 
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "parcels"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

        
  
