// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.kuba
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class Identifies : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Identifies\",\"namespace\":\"com.kuba\",\"fields\":[{\"name\":\"UP" +
				"ID\",\"type\":\"string\"},{\"name\":\"Barcode\",\"type\":\"string\"}]}");
		private string _UPID;
		private string _Barcode;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Identifies._SCHEMA;
			}
		}
		public string UPID
		{
			get
			{
				return this._UPID;
			}
			set
			{
				this._UPID = value;
			}
		}
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				this._Barcode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UPID;
			case 1: return this.Barcode;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UPID = (System.String)fieldValue; break;
			case 1: this.Barcode = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
