// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.kuba
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class ParcelEntity : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ParcelEntity"",""namespace"":""com.kuba"",""fields"":[{""name"":""_Id"",""type"":""string""},{""name"":""Identifies"",""type"":{""type"":""record"",""name"":""Identifies"",""namespace"":""com.kuba"",""fields"":[{""name"":""UPID"",""type"":""string""},{""name"":""Barcode"",""type"":""string""}]}},{""name"":""Attributes"",""type"":{""type"":""record"",""name"":""Attributes"",""namespace"":""com.kuba"",""fields"":[{""name"":""Weight"",""type"":""float""},{""name"":""Width"",""type"":""float""},{""name"":""Length"",""type"":""float""},{""name"":""Depth"",""type"":""float""}]}},{""name"":""CurrentState"",""type"":{""type"":""record"",""name"":""CurrentState"",""namespace"":""com.kuba"",""fields"":[{""name"":""Facility"",""type"":{""type"":""enum"",""name"":""Facility"",""namespace"":""com.kuba"",""symbols"":[""Ord"",""Wdr"",""Dfw"",""Atl""]}}]}}]}");
		private string @__Id;
		private com.kuba.Identifies _Identifies;
		private com.kuba.Attributes _Attributes;
		private com.kuba.CurrentState _CurrentState;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ParcelEntity._SCHEMA;
			}
		}
		public string _Id
		{
			get
			{
				return this.@__Id;
			}
			set
			{
				this.@__Id = value;
			}
		}
		public com.kuba.Identifies Identifies
		{
			get
			{
				return this._Identifies;
			}
			set
			{
				this._Identifies = value;
			}
		}
		public com.kuba.Attributes Attributes
		{
			get
			{
				return this._Attributes;
			}
			set
			{
				this._Attributes = value;
			}
		}
		public com.kuba.CurrentState CurrentState
		{
			get
			{
				return this._CurrentState;
			}
			set
			{
				this._CurrentState = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this._Id;
			case 1: return this.Identifies;
			case 2: return this.Attributes;
			case 3: return this.CurrentState;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this._Id = (System.String)fieldValue; break;
			case 1: this.Identifies = (com.kuba.Identifies)fieldValue; break;
			case 2: this.Attributes = (com.kuba.Attributes)fieldValue; break;
			case 3: this.CurrentState = (com.kuba.CurrentState)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
